# some example config
orthomosaic_dir: ../image_data/orthomosaic
orthomosaic_output_dir: ../image_data/orthomosaic_output


# just for testing
sample_orthomosaic_file: ../image_data/orthomosaic/20221206_FR_FW_Verbundsnetz_P2_transparent_mosaic_group1.tif


# some models path:
# Faster R-CNN
faster_rcnn: mainprocess/benchmark/faster_rcnn
faster_rcnn_output: outputs/faster_rcnn

# RetinaNet
retinanet: mainprocess/benchmark/retina_net
retinanet_output: outputs/retina_net

# Cascade R-CNN
cascade_rcnn: mainprocess/benchmark/cascade_rcnn
cascade_rcnn_ouput: outputs/cascade_rcnn

# yolov5
yolov5: mainprocess/benchmark/yolo_v5
yolov5_output: outputs/yolo_v5

# yolov8
yolov8: mainprocess/benchmark/yolo_v8
yolov8_output: outputs/yolo_v8

# DETR...