# some example config
orthomosaic_dir: ../image_data/orthomosaic
orthomosaic_output_dir: ../image_data/orthomosaic_output

# some models path:

# Faster R-CNN
faster_rcnn: mainprocess/models/faster_rcnn
faster_rcnn_output: outputs/faster_rcnn
faster_rcnn_model: trained_models/faster_rcnn

# RetinaNet
retinanet: mainprocess/models/retina_net
retinanet_output: outputs/retina_net
retinanet_model: trained_models/retina_net

# Cascade R-CNN
cascade_rcnn: mainprocess/models/cascade_rcnn
cascade_rcnn_output: outputs/cascade_rcnn
cascade_rcnn_model: trained_models/cascade_rcnn

# yolov8
yolov8: mainprocess/models/yolo_v8
yolov8_output: outputs/yolo_v8

# RE-DETR
yolov8: mainprocess/models/rt_detr
yolov8_output: outputs/rtdetr