model: rtdetr-x.pt # pre-trained model type, yolov8s, yolov8m would be great for small objects detection
data: /home/rdluhu/Dokumente/object_detection_project/datasets/dataset_yolo_aug/data.yaml
epochs: 120 # Increase epochs to compensate for limited data
batch: 4
imgsz: 640 # increase image size to help detect small objects
patience: 300 # number of epochs to wait without improvement # set a high value to disable early stopping
save: True # enables saving of training checkpoints
device: 0 # a single GPU, if there are other devices, change it
workers: 8 # number of work threads 
exist_ok : True
pretrained: True
lr0: 0.005 # lower to prevent overfitting
lrf: 0.01 # decay slowly for stability
momentum: 0.9
weight_decay: 0.0001
warmup_epochs: 5 # increase warmup epochs to stabilize learning
warmup_momentum: 0.9 # Slightly higher to prevent sudden jumps
warmup_bias_lr: 0.05 
cos_lr: True
box: 8.0
cls: 0.6
val: True
freeze: 10 # try to freeze all backbone
project: /home/rdluhu/Dokumente/object_detection_project/outputs/rtdetr
name: "exp_rtdetr_aug"
best_model: "/home/rdluhu/Dokumente/object_detection_project/trained_models/rtdetr/best.pt"