dataset:
  chess:
    name: "chess_dataset"
    image_root: "/Users/hoshikun/Documents/object-detect-dev/datasets/chess_coco"
    train_root: "/Users/hoshikun/Documents/object-detect-dev/datasets/chess_coco/train"
    test_root: "/Users/hoshikun/Documents/object-detect-dev/datasets/chess_coco/test"
    json_file_train: "/Users/hoshikun/Documents/object-detect-dev/datasets/chess_coco/train"
    json_file_test: "/Users/hoshikun/Documents/object-detect-dev/datasets/chess_coco/test"

  cityscapes:
    name: "urban_custom_dataset"
