
train_dir: ../../dataset.v10i.coco/train/
train_annotation: ../../dataset.v10i.coco/train/_annotations.coco.json
val_dir: ../../dataset.v10i.coco/valid/
val_annotation: ../../dataset.v10i.coco/valid/_annotations.coco.json
test_dir: ../../dataset.v10i.coco/test/
val_annotation: 
output_dir:

nc: 7 # number of classes
names: ['Gasschieberdeckel', 'Kanalschachtdeckel', 'Sinkkaesten', 'Unterflurhydrant', 'Versorgungsschachtdeckel', 'Wasserschieberdeckel', 'KanaldeckelQuad']

